### ISSUE TITLE
Blackman Permission issue

### ISSUE THREAD

**Issue by StryketheOrc** [BlackArch/blackman#9] opened 2017-12-25 15:38 UTC
![image](https://user-images.githubusercontent.com/6243762/34341156-51c5110a-e95f-11e7-9902-18ad6386735e.png)
Permission to create folders and install packages requires elevation, but an error check in this tool kicks you out if you are root or use sudo.

**Comment by PedroSFreitas** [comment] 2018-02-01 12:30
@StryketheOrc Blackman was updated and this issue **_should_** be fix by now.
Please consider running blackman again and if you find any issue report back to us. Thanks :+1:

**Comment by PedroSFreitas** [comment] 2018-02-06 13:50
@StryketheOrc I'm closing this Issue, as said above. `Blackman` was updated in the past week with an attempt to fix your issue. *I can't reproduce it* on the new version, so I believe it's safe to close this.

But if you find **the same** problem, reopen this Issue and provide further information.
Thanks.

**Closed by PedroSFreitas** 2018-02-06 13:50 UTC
